version: "3.0"
services:

  psi20_online_java:
    build:
      context: psi20_online_java
      dockerfile: Dockerfile
    image: "psi20-online-java"
    env_file:
      - .env
    links:
      - mongo
    ports:
      - 8080:8080


  psi20online_view:
    build:
      context: psi20online-view
      dockerfile: Dockerfile
    image: "psi20online-view"
    ports:
      - 4200:80

  psi20_web_scrapper:
    build:
      context: psi20_web_scrapper
      dockerfile: Dockerfile
    image: "psi20_web_scrapper"
    depends_on:
      - "mongo-seed"
    links:
      - mongo

  # MongoDB - Reactive Persistence
  mongo:
    build:
      context: mongo
      dockerfile: Dockerfile
    image: "mongodb"
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    env_file:
      - .env

  # The mongo-seed container is just for waiting until the main mongo container is done setting its replicaset up
  # and then initializing data.
  mongo-seed:
    build:
      context: mongo_seed
      dockerfile: Dockerfile
    # ping the main mongo instance relentlessly until the connection is ready, then wait, then run an initialize data script to populate data.
    command: bash -c "until mongo mongo:27017/psi20_online; do echo 'Waiting for Mongo to be ready...'; sleep 1; done; sleep 3; mongo mongo:27017/psi20_online init.js; "
    depends_on:
      - "mongo"
    links:
      - mongo

volumes:
  mongodata: